spring:
  datasource:
    url: jdbc:mysql://192.168.1.118:3306/comadmin?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    #切换数据源，如果不写，会使用默认的
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    # 以下是DuriDataSource的基本配置，如果不写，使用springboot默认的
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接.
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    #获取连接时执行检测，建议关闭，影响性能
    testOnBorrow: false
    #归还连接时执行检测，建议关闭，影响性能
    testOnReturn: false
    #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大,
    poolPreparedStatements: true
    # oracle建议开启，mysql下建议关闭
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #stat:监控统计  log4j:日志  wall:防御sql注入
    filters: stat,wall,log4j
    #开启poolPreparedStatements后生效
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    #通过connectProperties属性来打开mergeSql功能;慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-idle: 8
        min-idle: 1
        max-active: 20
        max-wait: 2

mybatis-plus:
  #打印SQL
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.zfl.entity.*

#rocketmq:
#  namesrvAddr: 192.168.1.118:9876
#  #过期订单消息配置
#  orderPast:
#    consumerGroup: order_past_consumer
#    producerGroup: order_past_producer
#    topic: order_past_topic
#    tags: order_past_tags

#rocketmq:
#  namesrvAddr: localhost:9876
#  #过期订单消息配置
#  orderPast:
#    consumerGroup: order_past_consumer
#    producerGroup: order_past_producer
#    topic: order_past_topic
#    tags: order_past_tags

#避免创建事务失败
logging:
  level:
    com.zfl.mapper: debug



server:
  port: 8081
